# Generated by Django 3.0.8 on 2023-05-25 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='declaration',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
    ]
