# Generated by Django 3.0.14 on 2023-05-13 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_auto_20230513_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок объявления')),
                ('residential_complex', models.CharField(max_length=250, verbose_name='Название ЖК')),
                ('description', models.TextField(verbose_name='Описание объявления')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('Metro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.Metro', verbose_name='Метро')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.City', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
